/**
 * Precomputes how often each of the 169 starting hands flops two pair or better.
 *
 * The design brief asks for the range grid to be shaded "in varying intensities
 * to indicate strategic EV distributions". Preflop equity would be the natural
 * quantity and it is not computable here: exact equity against a random hand
 * means every opponent holding against every runout, which is on the order of a
 * billion evaluations per starting hand. Monte Carlo would get there, and this
 * project does not sample.
 *
 * So the grid is shaded by something that IS exactly computable and is worth
 * knowing: over all 19,600 possible flops, how often do these two cards make
 * two pair or better. Nineteen thousand flops times 169 hands is three million
 * evaluations, which is seconds, and the answer is exact.
 *
 * "Pair or better" was the first attempt and it was useless as a heatmap. It is
 * dominated by the chance of pairing one of your own two cards, which barely
 * changes between hands, so every non-pair cell landed between 46.1% and 48.3%
 * and the grid was flat. Two pair or better spreads from about 2% to about 12%,
 * and it separates the hands that can flop a straight or a flush from the ones
 * that cannot - which is the distinction a range chart exists to show.
 *
 * Suits are interchangeable before any board exists, so one representative
 * combination per class is not an approximation - AhKh has precisely the same
 * distribution as AsKs. The property test checks a second representative of
 * each class agrees to the last runout.
 *
 * Run with: npx tsx scripts/build-flop-strength.ts
 * Writes:   lib/poker/flop-strength.ts
 */

import { writeFileSync } from "node:fs";
import { RANKS } from "../lib/cards";
import { encode, categorise5, ONE_PAIR } from "../lib/poker/hand";
import type { CardCode, Suit } from "../components/cards/PlayingCard";

type Shape = "pair" | "suited" | "offsuit";

/** One representative combination for a class. Suits do not matter yet. */
function representative(
  highIndex: number,
  lowIndex: number,
  shape: Shape,
  altSuits = false
): [CardCode, CardCode] {
  const high = RANKS[highIndex];
  const low = RANKS[lowIndex];
  const [a, b]: [Suit, Suit] = altSuits ? ["d", "c"] : ["s", "h"];

  if (shape === "pair") return [`${high}${a}`, `${high}${b}`];
  if (shape === "suited") return [`${high}${a}`, `${low}${a}`];
  return [`${high}${a}`, `${low}${b}`];
}

/** Share of all flops on which these two cards hold two pair or better. */
function flopStrength(hole: [CardCode, CardCode]): number {
  const dead = new Set(hole.map(encode));
  const deck: number[] = [];
  for (let card = 0; card < 52; card++) if (!dead.has(card)) deck.push(card);

  const [h1, h2] = hole.map(encode);
  const five = [h1, h2, 0, 0, 0];

  let made = 0;
  let flops = 0;

  for (let i = 0; i < deck.length - 2; i++) {
    five[2] = deck[i];
    for (let j = i + 1; j < deck.length - 1; j++) {
      five[3] = deck[j];
      for (let k = j + 1; k < deck.length; k++) {
        five[4] = deck[k];
        flops++;
        if (categorise5(five) > ONE_PAIR) made++;
      }
    }
  }

  return made / flops;
}

const started = Date.now();
const rows: string[] = [];
let cells = 0;

for (let row = 0; row < 13; row++) {
  const values: string[] = [];
  for (let col = 0; col < 13; col++) {
    const shape: Shape = row === col ? "pair" : col > row ? "suited" : "offsuit";
    const high = Math.min(row, col);
    const low = Math.max(row, col);
    const share = flopStrength(representative(high, low, shape));

    // A second representative must agree exactly, or suits are leaking into
    // the count somewhere.
    const check = flopStrength(representative(high, low, shape, true));
    if (Math.abs(share - check) > 1e-12) {
      throw new Error(
        `suit dependence at row ${row} col ${col}: ${share} vs ${check}`
      );
    }

    values.push((Math.round(share * 10000) / 10000).toFixed(4));
    cells++;
  }
  rows.push(`  [${values.join(", ")}],`);
}

const flat = rows.join("\n");
const all = flat.match(/0\.\d+/g)!.map(Number);
const min = Math.min(...all);
const max = Math.max(...all);

const file = `// GENERATED by scripts/build-flop-strength.ts - do not edit by hand.
//
// For each of the 169 starting hands, the exact share of the 19,600 possible
// flops on which it holds TWO PAIR OR BETTER. Enumerated, not sampled: every
// flop is dealt and counted.
//
// Rows and columns are RANKS order, ace first. Above the diagonal is suited,
// below it is offsuit, the diagonal is the pocket pairs. This is what shades
// the range grid, and the grid says so on screen.

export const FLOP_STRENGTH: number[][] = [
${flat}
];

/** Range of the table, so a colour ramp can normalise against it. */
export const FLOP_STRENGTH_MIN = ${min};
export const FLOP_STRENGTH_MAX = ${max};
`;

writeFileSync("lib/poker/flop-strength.ts", file);

console.log(`cells          ${cells}`);
console.log(`flops each     19,600 (enumerated)`);
console.log(`weakest        ${(min * 100).toFixed(1)}%`);
console.log(`strongest      ${(max * 100).toFixed(1)}%`);
console.log(`elapsed        ${((Date.now() - started) / 1000).toFixed(1)}s`);
console.log(`wrote          lib/poker/flop-strength.ts`);
